version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - .:/app
      - go_cache:/go/pkg/mod/cache

volumes:
  go_cache: